### ISSUE TITLE
Allow specifying target directory for `DOCS-BUILDER:BUILD`

### ISSUE THREAD

**Issue by mathrick** [40ants/docs-builder#3]
Currently there's no way to influence where `BUILD` will write generated docs, and it just assumes it knows where to write them, which is pretty inconvenient and inflexible. It also does the guessing separately for each and every builder, meaning they can pick different output directories, and it's not documented in any way, so there's no way for the user to know, other than to let it write wherever it wants and look at the returned path.

**Comment by svetlyak40wt** [comment]
Sadly, it is not always possible to make some documentation generator to use a particular directory for output.

Probably, we could add an optional keyword argument and if it is given, then to move documentation to the given folder.

I think, this might be a good "first issue" to solve! Would you like to make a pull-request?

**Comment by mathrick** [comment]
Yup, I can do that.

**Comment by svetlyak40wt** [comment]
@mathrick did you solve this problem for yourself somehow?
